import math

# 提取自项目 Spec 的 e^x 参数表 (N=32) [cite: 76]
boundaries_float = [
    -6.0472, -5.0710, -4.4169, -3.9245, -3.5296, -3.1999, -2.9169, -2.6691,
    -2.4485, -2.2499, -2.0692, -1.9036, -1.7505, -1.6084, -1.4757, -1.3513,
    -1.2341, -1.1234, -1.0186, -0.9189, -0.8240, -0.7334, -0.6467, -0.5636,
    -0.4839, -0.4071, -0.3333, -0.2620, -0.1932, -0.1267, -0.0624, 0.0000
]

slopes_float = [
    0.00103904, 0.00400703, 0.00886024, 0.01559805, 0.02422040, 0.03472731, 0.04711869, 0.06139471,
    0.07755546, 0.09560075, 0.11553054, 0.13734482, 0.16104408, 0.18662848, 0.21409756, 0.24345127,
    0.27468957, 0.30781242, 0.34281982, 0.37971297, 0.41849213, 0.45915617, 0.50170509, 0.54613888,
    0.59245750, 0.64066088, 0.69074895, 0.74272169, 0.79657909, 0.85232113, 0.90994779, 0.96945907
]

intercepts_float = [
    0.00841221, 0.02636020, 0.05097089, 0.08073098, 0.11456940, 0.15165456, 0.19130587, 0.23294800,
    0.27608185, 0.32026619, 0.36510646, 0.41024562, 0.45535854, 0.50014519, 0.54432670, 0.58764415,
    0.62985526, 0.67073248, 0.71006122, 0.74763964, 0.78327500, 0.81678276, 0.84798811, 0.87672399,
    0.90283041, 0.92615389, 0.94654699, 0.96386783, 0.97797971, 0.98875070, 0.99605334, 0.99976435
]


# 浮点数转有符号十六进制定点数
def float_to_signed_hex(val, frac_bits, total_bits=16):
    scaled_val = int(round(val * (1 << frac_bits)))
    max_val = (1 << (total_bits - 1)) - 1
    min_val = -(1 << (total_bits - 1))
    scaled_val = max(min(scaled_val, max_val), min_val)

    # 转为补码以便生成 Hex
    hex_val = scaled_val if scaled_val >= 0 else (1 << total_bits) + scaled_val
    return f"{total_bits}'sh{hex_val:04X}"  # 使用 'sh 显式标记有符号 Hex


# 生成内容
output_str = "// --- e^x NPLA Parameters (Strictly Signed) ---\n"
output_str += "// Generated by Python Script\n\n"

output_str += "// Boundaries (Format: Q4.12 Signed)\n"
for i, b in enumerate(boundaries_float):
    if i < 31:
        hex_val = float_to_signed_hex(b, 12)
        output_str += f"localparam signed [15:0] BND_{i:02d} = {hex_val}; // {b}\n"

output_str += "\n// Slopes 'a' (Format: Q2.14 Signed)\n"
for i, a in enumerate(slopes_float):
    hex_val = float_to_signed_hex(a, 14)
    output_str += f"localparam signed [15:0] COEF_A_{i:02d} = {hex_val}; // {a}\n"

output_str += "\n// Intercepts 'b' (Format: Q2.14 Signed)\n"
for i, b in enumerate(intercepts_float):
    hex_val = float_to_signed_hex(b, 14)
    output_str += f"localparam signed [15:0] COEF_B_{i:02d} = {hex_val}; // {b}\n"

with open("exp_params.vh", "w") as f:
    f.write(output_str)

print("生成成功！已更新为 signed [15:0] 和 'sh 格式。")